name: Climate Archive

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"  # Run every day at 1am only on the main branch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Jupyter, Nbconvert, and Required Libraries
        run: |
          python -m pip install --upgrade pip 
          pip install .
          
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          /usr/local/bin/aws --version


      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set -x
          /usr/local/bin/aws  --version
          /usr/local/bin/aws  configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          /usr/local/bin/aws  configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          /usr/local/bin/aws  configure set default.region us-west-2

          mkdir -p data
          # Get today's, yesterday's, and tomorrow's dates in the format YYYY-MM-DD
          TODAY=$(date '+%Y-%m-%d')
          YESTERDAY=$(date -d 'yesterday' '+%Y-%m-%d')
          TOMORROW=$(date -d 'tomorrow' '+%Y-%m-%d')

          # Sync only the required folders from S3
          for DATE in "$YESTERDAY" "$TODAY" "$TOMORROW"; do
            aws s3 sync "s3://microgreen-dev-esp32/dev/climate/ESP32-C3-84:FC:E6:01:09:B0/$DATE/" "data/$DATE" --only-show-errors
          done

      - name: Run
        env:
          CONFLUENCE_URL: ${{ vars.CONFLUENCE_URL }}
          CONFLUENCE_SPACE_KEY: ${{ vars.CONFLUENCE_SPACE_KEY }}
          CONFLUENCE_USERNAME: ${{ vars.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        run: |
          climate-realtime
          mv *.svg publication/source/climate
          
          cd publication
          make confluence

#      - name: Commit and Push to Different Branch
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git config --global user.name 'github-actions'
#          git config --global user.email 'actions@github.com'
#          git checkout -B report
#          git add temperature.ipynb
#          git commit -m 'Update temperature notebook output'
#          git push --force origin report